"""
etl_insentif.py
ETL Insentif - ZSDCONUN -> Achievement SDO -> Insentif Q1

Pipeline:
  1. Load source xlsx
  2. Transform (clean SDO, enrich, classify, brand dari MASTERDATA)
  3. Dedupe billing triplicates (DOCNUM+ITEM#+ACTUAL PGI DATE)
  4. Pivot achievement Q1 per SDO (filter FILTER_CHANNEL + nama SDO)
  5. Hitung insentif per cycle + insentif quarterly
  6. Save outputs dengan formatting Excel

Author : generated by Claude
Usage  : python etl_insentif.py
"""

from __future__ import annotations

import warnings
from pathlib import Path

import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import (
    PatternFill, Font, Alignment, Border, Side, numbers
)
from openpyxl.utils import get_column_letter

warnings.filterwarnings("ignore", category=UserWarning)

# =====================================================================
# 1. CONFIG
# =====================================================================

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
OUT_DIR = BASE_DIR / "output"
OUT_DIR.mkdir(exist_ok=True)

# Source files
FILE_ZSDCONUN = DATA_DIR / "ZSDCONUN 23112025 -30042026.xlsx"
FILE_CYCLE = DATA_DIR / "CYCLE_REKAP_1.0.xlsx"
FILE_SKU = DATA_DIR / "skuu6.xlsx"  # dipakai sheet MASTERDATA untuk Brand
FILE_CUST = DATA_DIR / "master c05.xlsx"
FILE_TARGET = DATA_DIR / "Target Modern Update KA 15 May 2026.xlsx"

# Sheet names
SHEET_ZSDCONUN = "ZSDCONUN"
SHEET_CYCLE = "Sheet2"
SHEET_SKU_MASTER = "MASTERDATA"  # kolom Brand ada di sini
SHEET_CUST = "Sheet1"
SHEET_TARGET = "Target KA (2)"

# Business constants
PPN = 1.11
Q1_CYCLES = ["C0126", "C0226", "C0326"]
Q1_CYCLE_NUM = ["C01", "C02", "C03"]
FILTER_REMARKS = ["SALES", "RETUR"]  # Claim G di-exclude dari achievement
DROP_INVALID_SO_DATE = True

# Filter channel untuk pivot achievement (set None untuk semua channel)
# Contoh: "MODERN TRADE" / "DIRECT" / "INDIRECT" / None
FILTER_CHANNEL = 'MODERN TRADE'  # None = semua channel, atau set "MODERN TRADE" / "DIRECT" / dll

# Daftar SDO yang dihitung insentifnya (semua SDO di Target KA)
SDO_INSENTIF_LIST = [
    "MARTA TEMMY NATASIA",
    "IMANUEL SIREGAR",
    "BAGUS YULIARTO",
    "ANDY",
    "AHMAD DAMYATI",
    "JEKY TIRTA",
    "MOHAMMAD HENDRA FARIZAL",
]

# Tabel tier insentif per cycle (berdasarkan ACH% per cycle)
# >= 80% - < 100%  -> 0.25%
# >= 100% - <= 110% -> 0.50%
# > 110%            -> 0.75%
TIER_CYCLE_PCT = [0.0025, 0.0050, 0.0075]
TIER_CYCLE_THRESH = [0.80, 1.00, 1.10]  # batas bawah tier

# Tabel tier insentif quarterly (ADD) — VLOOKUP dari scheme C34:D38
# Format: list of (batas_bawah_ach, nilai_add)
# Jika ach < 0.90 -> 0
# 0.90 <= ach < 1.00 -> 0.001 (0.10%)
# 1.00 <= ach < 1.05 -> 0.0025 (0.25%)
# 1.05 <= ach < 1.10 -> 0.003 (0.30%)
# ach >= 1.10       -> 0.0035 (0.35%)
TIER_QUARTERLY = [
    (0.00, 0.0000),
    (0.90, 0.0010),
    (1.00, 0.0025),
    (1.05, 0.0030),
    (1.10, 0.0035),
]


# =====================================================================
# 2. SDO CLEANING  (dipanggil diawal ETL, bukan dari merge master)
# =====================================================================

def cleaning_sdo_global(s):
    """Normalisasi nama SDO dari kolom SDO di ZSDCONUN."""
    if pd.isna(s):
        return None
    s = str(s).upper().strip()
    if "ANDY WIJAYA" in s:
        return "ANDY"
    elif "IMAM SHOVI" in s:
        return "IMAM SHOVII"
    elif "OKTO" in s:
        return "OKTO RISMAN"
    elif "ANDI MANGGALA" in s or "ANDI ARDIYANSYAH" in s:
        return "ANDI MANGGALA PUTRA"
    elif "JINO" in s:
        return "FREEKY JINO"
    elif "MUHAMMAD LANANG GALIH" in s:
        return "MUHAMMAD LANANG GALIH GUMILANG"
    elif "ABDUL JABBAR" in s:
        return "ABDUL JABAR"
    elif "MO MOHAMMAD HENDRA FARIZAL" in s:
        return "MOHAMMAD HENDRA FARIZAL"
    else:
        return s


# =====================================================================
# 3. LOAD
# =====================================================================

def load_data() -> dict:
    """Baca semua source ke dict of DataFrame."""
    print("[1/6] Loading source data...")

    data = {
        "zsdconun": pd.read_excel(FILE_ZSDCONUN, sheet_name=SHEET_ZSDCONUN, engine="openpyxl"),
        "cycle": pd.read_excel(FILE_CYCLE, sheet_name=SHEET_CYCLE, engine="openpyxl"),
        # Brand ada di sheet MASTERDATA, bukan LIST SKU
        "sku_master": pd.read_excel(FILE_SKU, sheet_name=SHEET_SKU_MASTER, engine="openpyxl"),
        "cust": pd.read_excel(FILE_CUST, sheet_name=SHEET_CUST, engine="openpyxl"),
        "target": pd.read_excel(FILE_TARGET, sheet_name=SHEET_TARGET, engine="openpyxl"),
    }

    for k, v in data.items():
        print(f"   - {k:<12s} : {len(v):>7,} rows x {len(v.columns):>3} cols")
    return data


# =====================================================================
# 4. TRANSFORM
# =====================================================================

def _clean_zsdconun(df: pd.DataFrame) -> pd.DataFrame:
    """Drop baris invalid + normalisasi tipe data + cleaning SDO."""
    df = df.copy()

    # 1) Cleaning SDO diawal (sebelum merge apapun)
    df["SDO"] = df["SDO"].apply(cleaning_sdo_global)

    # 2) Drop baris dengan SO DATE = '#VALUE!' (rusak di source)
    if DROP_INVALID_SO_DATE:
        mask_invalid = df["SO DATE"].astype(str).str.contains("VALUE", na=False)
        n_drop = int(mask_invalid.sum())
        if n_drop:
            print(f"   drop {n_drop:,} rows with invalid SO DATE")
            df = df[~mask_invalid].copy()

    # 3) ACTUAL PGI DATE → datetime
    df["ACTUAL PGI DATE"] = pd.to_datetime(df["ACTUAL PGI DATE"], errors="coerce")
    df = df.dropna(subset=["ACTUAL PGI DATE"]).reset_index(drop=True)

    # 4) Normalisasi key
    df["CUSTOMER#"] = df["CUSTOMER#"].astype(str).str.strip()
    df["MATERIAL"] = df["MATERIAL"].astype(str).str.strip()

    return df


def _build_cycle_map(cycle_df: pd.DataFrame) -> pd.DataFrame:
    """Siapkan cycle_df: kolom Cycle, Start, End sebagai datetime."""
    c = cycle_df[["Cycle", "Start Date", "End Date"]].dropna(subset=["Cycle"]).copy()
    c["Start Date"] = pd.to_datetime(c["Start Date"], errors="coerce")
    c["End Date"] = pd.to_datetime(c["End Date"], errors="coerce")
    c = c.dropna(subset=["Start Date", "End Date"]).reset_index(drop=True)
    return c


def _assign_cycle(df: pd.DataFrame, cycle_df: pd.DataFrame) -> pd.Series:
    """Untuk setiap baris, cari cycle yang ACTUAL PGI DATE-nya di antara Start–End."""
    c_sorted = cycle_df.sort_values("Start Date").reset_index(drop=True)
    starts = c_sorted["Start Date"].values
    ends = c_sorted["End Date"].values
    cycles = c_sorted["Cycle"].values
    pgi = df["ACTUAL PGI DATE"].values

    import numpy as np
    idx = np.searchsorted(starts, pgi, side="right") - 1
    result = []
    for i, ix in enumerate(idx):
        if 0 <= ix < len(cycles) and starts[ix] <= pgi[i] <= ends[ix]:
            result.append(cycles[ix])
        else:
            result.append(None)
    return pd.Series(result, index=df.index, name="CYCLE")


def _prepare_sku_master(sku_df: pd.DataFrame) -> pd.DataFrame:
    """Ambil kolom Brand, PG, SUB-PG dari sheet MASTERDATA + dedupe SKU Code."""
    s = sku_df[["SKU Code", "Brand", "PG", "SUB-PG"]].copy()
    s.columns = ["SKU Code", "BRAND_SRC", "PG_SRC", "SUBPG_SRC"]
    s["SKU Code"] = s["SKU Code"].astype(str).str.strip()
    s = s.dropna(subset=["SKU Code"])
    s = s.drop_duplicates(subset=["SKU Code"], keep="first").reset_index(drop=True)
    return s


def _prepare_cust(cust_df: pd.DataFrame) -> pd.DataFrame:
    """Ambil Chanel, SPV, ASM, RSM dari master c05 + dedupe Customer Code."""
    c = cust_df[["Customer Code", "Chanel", "SPV", "ASM", "RSM"]].copy()
    c.columns = ["CUSTOMER#", "CHANNEL_SRC", "SPV_SRC", "ASM_SRC", "RSM_SRC"]
    c["CUSTOMER#"] = c["CUSTOMER#"].astype(str).str.strip()
    c = c.dropna(subset=["CUSTOMER#"])
    c = c.drop_duplicates(subset=["CUSTOMER#"], keep="first").reset_index(drop=True)
    return c


def _classify_remarks(netvalue2: float) -> str:
    """Logika remarks: <0 RETUR, <1000 CLAIM G, >=1000 SALES."""
    if pd.isna(netvalue2):
        return None
    if netvalue2 < 0:
        return "RETUR"
    if netvalue2 < 1000:
        return "CLAIM G"
    return "SALES"


def transform(data: dict) -> pd.DataFrame:
    """Inti transformasi ZSDCONUN → ETL enriched."""
    print("[2/6] Transforming ZSDCONUN...")

    df = _clean_zsdconun(data["zsdconun"])
    print(f"   rows after clean + SDO cleaning: {len(df):,}")

    # 1) NET VALUE2 = NET VALUE × PPN
    df["NET VALUE2"] = df["NET VALUE"] * PPN

    # 2) CYCLE: lookup berdasarkan ACTUAL PGI DATE
    cycle_map = _build_cycle_map(data["cycle"])
    df["CYCLE"] = _assign_cycle(df, cycle_map)
    n_assigned = df["CYCLE"].notna().sum()
    n_total = len(df)
    print(f"   cycle assigned: {n_assigned:,} / {n_total:,} ({n_assigned/n_total*100:.1f}%)")

    # 3) BRAND, PG, SUBPG: merge MATERIAL → skuu6 MASTERDATA
    sku = _prepare_sku_master(data["sku_master"])
    df = df.merge(sku, how="left", left_on="MATERIAL", right_on="SKU Code")
    df["BRAND"] = df["BRAND_SRC"]
    df["PG"] = df["PG_SRC"]
    df["SUBPG"] = df["SUBPG_SRC"]
    df["SUBPG1"] = df["SUBPG_SRC"]  # alias
    df = df.drop(columns=["SKU Code", "BRAND_SRC", "PG_SRC", "SUBPG_SRC"], errors="ignore")

    # 4) CHANNEL: merge CUSTOMER# → master c05
    cust = _prepare_cust(data["cust"])
    df = df.merge(cust, how="left", on="CUSTOMER#")
    df["CHANNEL"] = df["CHANNEL_SRC"]
    df["SPV"] = df["SPV_SRC"]
    df["ASM"] = df["ASM_SRC"]
    df["RSM"] = df["RSM_SRC"]
    df = df.drop(columns=["CHANNEL_SRC", "SPV_SRC", "ASM_SRC", "RSM_SRC"], errors="ignore")

    # 5) REMARKS
    df["REMARKS"] = df["NET VALUE2"].apply(_classify_remarks)

    # 6) CUST_TYPE (reserved, None)
    df["CUST_TYPE"] = None

    # Susun ulang kolom sesuai output referensi
    output_cols = [
        "TYPE", "CUSTOMER#", "NAME1", "NAME2", "CUST GRP", "SALES GRP", "SDO",
        "DOCNUM", "SO DATE", "DOCDATE", "BILLINGDATE", "ACTUAL PGI DATE",
        "ITEM#", "MATERIAL", "DESCRIPTION", "ITEM CAT", "PLANT", "STORELOC",
        "QUANTITY", "SO AMOUNT", "DISCOUNT", "NET VALUE", "NET VALUE2",
        "CYCLE", "BRAND", "PG", "SUBPG", "SUBPG1", "CHANNEL", "REMARKS",
        "CUST_TYPE", "SPV", "ASM", "RSM",
    ]
    df = df.reindex(columns=output_cols)

    # --- FIX: dedupe billing triplicates ---
    # SAP bisa menghasilkan multiple billing document (BILLINGDATE berbeda)
    # untuk 1 delivery item (DOCNUM + ITEM# + ACTUAL PGI DATE sama).
    # Ambil 1 baris per kombinasi unik → hindari double-count di pivot.
    # before = len(df)
    # df = df.drop_duplicates(subset=["DOCNUM", "ITEM#", "ACTUAL PGI DATE"], keep="first")
    # n_removed = before - len(df)
    # if n_removed:
    #     print(f"   dedupe billing triplicates: -{n_removed:,} rows removed")

    # print(f"   ETL rows: {len(df):,}")
    return df


# =====================================================================
# 5. PIVOT & INSENTIF
# =====================================================================

def _get_target_quarters(target_df: pd.DataFrame) -> pd.DataFrame:
    """Ambil target per cycle dan Q1 per SDO."""
    t = target_df.copy()
    t.columns = [str(c).strip() for c in t.columns]
    t = t.rename(columns={t.columns[0]: "SDO"})
    t["SDO"] = t["SDO"].astype(str).str.strip().str.upper()
    t = t[t["SDO"].notna() & (t["SDO"] != "TOTAL") & (t["SDO"] != "NONE") & (t["SDO"] != "")]
    # Ambil C01–C12 per cycle
    cycle_cols = [c for c in t.columns if c.startswith("C0") and c[1:].isdigit()]
    out = t[["SDO"] + cycle_cols].copy()
    out["Target_Q1"] = out[["C01", "C02", "C03"]].sum(axis=1)
    return out.reset_index(drop=True)


def _filter_sdo_insentif(df_etl: pd.DataFrame) -> pd.DataFrame:
    """Filter SDO list + remarks SALES/RETUR + FILTER_CHANNEL (jika diset)."""
    sdo_set = {s.upper().strip() for s in SDO_INSENTIF_LIST}
    df_etl = df_etl.copy()
    df_etl["SDO"] = df_etl["SDO"].astype(str).str.strip().str.upper()
    mask = df_etl["SDO"].isin(sdo_set) & df_etl["REMARKS"].isin(FILTER_REMARKS)

    # Tambahan filter channel
    if FILTER_CHANNEL:
        mask = mask & (df_etl["CHANNEL"].astype(str).str.upper() == FILTER_CHANNEL.upper())

    return df_etl[mask].copy()


def build_pivot_q1(df_etl: pd.DataFrame) -> pd.DataFrame:
    """Pivot: SDO × cycle, filter SDO list + FILTER_CHANNEL + SALES/RETUR."""
    ch_label = FILTER_CHANNEL if FILTER_CHANNEL else "ALL"
    print(f"[3/6] Building pivot Q1 (channel={ch_label}, SALES+RETUR)...")

    filtered = _filter_sdo_insentif(df_etl)
    print(f"   filtered rows: {len(filtered):,}")

    pivot = filtered.pivot_table(
        index="SDO",
        columns="CYCLE",
        values="NET VALUE2",
        aggfunc="sum",
        fill_value=0,
    )

    # Pastikan kolom Q1 ada
    for c in Q1_CYCLES:
        if c not in pivot.columns:
            pivot[c] = 0
    pivot = pivot[Q1_CYCLES]

    # Pastikan semua SDO di list muncul walaupun 0
    pivot = pivot.reindex([s.upper().strip() for s in SDO_INSENTIF_LIST], fill_value=0)

    pivot["Total_Q1"] = pivot[Q1_CYCLES].sum(axis=1)
    pivot = pivot.reset_index()
    print(f"   pivot rows: {len(pivot)}")
    return pivot


def _tier_pct(ach_pct: float) -> str:
    """Label tier per cycle: 0.25% / 0.5% / 0.75% / -"""
    if ach_pct < TIER_CYCLE_THRESH[0] * 100:
        return "< 80%"
    if ach_pct < TIER_CYCLE_THRESH[1] * 100:
        return "0.25%"
    if ach_pct <= TIER_CYCLE_THRESH[2] * 100:
        return "0.50%"
    return "0.75%"


def _nilai_per_cycle(tier: str, target: float, ach: float) -> float:
    """Nilai insentif per cycle sesuai scheme:
       0.25% -> ach * 0.25%
       0.5%  -> target * 0.25% + (ach - target) * 0.5%
       0.75% -> target * 0.25% + (ach - target) * 0.75%
       <80%  -> 0
    """
    if tier == "0.25%":
        return ach * TIER_CYCLE_PCT[0]
    if tier == "0.50%":
        return target * TIER_CYCLE_PCT[0] + max(ach - target, 0) * TIER_CYCLE_PCT[1]
    if tier == "0.75%":
        return target * TIER_CYCLE_PCT[0] + max(ach - target, 0) * TIER_CYCLE_PCT[2]
    return 0.0


def _tier_quarterly(ach_ratio: float) -> tuple[str, float]:
    """VLOOKUP add-on quarterly: return (label, nilai_add) dari TIER_QUARTERLY."""
    # TIER_QUARTERLY sorted ascending by threshold
    for thresh, val in reversed(TIER_QUARTERLY):
        if ach_ratio >= thresh:
            return (f"{val*100:.2f}%", val)
    return ("0.00%", 0.0)


def _nilai_quarterly(ach_q1: float, target_q1: float) -> tuple[float, str, float]:
    """Insentif quarterly (ADD):
       ach_ratio = ach_q1 / target_q1
       if ach_ratio < 0.90 -> 0
       else -> (target_q1 * 0.10%) + (ach_q1 - target_q1) * tier_value
    """
    if target_q1 <= 0:
        return (0.0, "0.00%", 0.0)
    ach_ratio = ach_q1 / target_q1
    label, val = _tier_quarterly(ach_ratio)
    if ach_ratio < TIER_QUARTERLY[1][0]:  # < 0.90
        return (0.0, label, ach_ratio)
    if ach_ratio < 1.00:
        return (ach_q1 * val, label, ach_ratio)
    # ach_ratio >= 1.00
    return (target_q1 * 0.001 + max(ach_q1 - target_q1, 0) * val, label, ach_ratio)


def hitung_insentif_q1(pivot: pd.DataFrame, target_df: pd.DataFrame) -> pd.DataFrame:
    """Hitung insentif Q1 per SDO:
       - per cycle (3 kolom cycle)
       - quarterly add-on
       - total
    """
    print("[4/6] Menghitung insentif Q1 (per cycle + quarterly)...")

    pivot = pivot.copy()
    target_df = target_df.copy()
    pivot["SDO"] = pivot["SDO"].astype(str).str.strip().str.upper()
    target_df["SDO"] = target_df["SDO"].astype(str).str.strip().str.upper()

    # Pastikan urutan SDO sesuai SDO_INSENTIF_LIST
    pivot = pivot.set_index("SDO")
    sdo_order = [s.upper().strip() for s in SDO_INSENTIF_LIST]
    pivot = pivot.reindex(sdo_order, fill_value=0).reset_index()

    # Merge target
    target_q1 = target_df[["SDO", "C01", "C02", "C03"]].copy()
    target_q1.columns = ["SDO", "Tgt_C01", "Tgt_C02", "Tgt_C03"]
    merged = pivot.merge(target_q1, on="SDO", how="left").fillna(0)

    # Hitung per cycle
    for i, cyc in enumerate(Q1_CYCLES):
        tgt_col = f"Tgt_{Q1_CYCLE_NUM[i]}"
        ach_col = cyc
        pct_col = f"ACH%_{Q1_CYCLE_NUM[i]}"
        tier_col = f"Tier_{Q1_CYCLE_NUM[i]}"
        nilai_col = f"Nilai_{Q1_CYCLE_NUM[i]}"

        merged[pct_col] = merged.apply(
            lambda r: (r[ach_col] / r[tgt_col] * 100) if r[tgt_col] > 0 else 0.0,
            axis=1,
        )
        merged[tier_col] = merged[pct_col].apply(_tier_pct)
        merged[nilai_col] = merged.apply(
            lambda r: _nilai_per_cycle(r[tier_col], r[tgt_col], r[ach_col]),
            axis=1,
        )

    # Total & ACH% Q1
    merged["Target_Q1"] = merged[["Tgt_C01", "Tgt_C02", "Tgt_C03"]].sum(axis=1)
    merged["Ach_Q1"] = merged["Total_Q1"]
    merged["ACH_pct"] = merged.apply(
        lambda r: (r["Ach_Q1"] / r["Target_Q1"] * 100) if r["Target_Q1"] > 0 else 0.0,
        axis=1,
    )

    # Insentif quarterly (ADD)
    q_results = merged.apply(
        lambda r: _nilai_quarterly(r["Ach_Q1"], r["Target_Q1"]),
        axis=1,
    )
    merged["Tier_Quarterly"] = [q[1] for q in q_results]
    merged["Add_Quarterly"] = [q[0] for q in q_results]
    merged["ACH_ratio"] = [q[2] for q in q_results]

    # Total insentif = jumlah 3 cycle + ADD quarterly
    merged["Total_Insentif"] = (
        merged["Nilai_C01"] + merged["Nilai_C02"] + merged["Nilai_C03"] + merged["Add_Quarterly"]
    )

    # Tier ringkasan Q1 (berdasarkan ACH_pct Q1)
    merged["Tier"] = merged["ACH_pct"].apply(_tier_pct)

    # Susun kolom output
    out_cols = [
        "SDO",
        "C0126", "C0226", "C0326", "Total_Q1",
        "Tgt_C01", "Tgt_C02", "Tgt_C03", "Target_Q1",
        "ACH%_C01", "Tier_C01", "Nilai_C01",
        "ACH%_C02", "Tier_C02", "Nilai_C02",
        "ACH%_C03", "Tier_C03", "Nilai_C03",
        "ACH_pct", "Tier",
        "Tier_Quarterly", "Add_Quarterly",
        "Total_Insentif",
    ]
    merged = merged[out_cols].sort_values("ACH_pct", ascending=False).reset_index(drop=True)
    return merged


# =====================================================================
# 6. SAVE
# =====================================================================

def _fmt_insentif_sheet(ws, insentif: pd.DataFrame) -> None:
    """Apply rich formatting ke sheet Insentif."""
    # ---- Colour palette ----
    C_HEADER_DARK  = "1F3864"   # navy
    C_HEADER_MID   = "2E75B6"   # blue
    C_HEADER_LIGHT = "D6E4F0"   # light blue
    C_CYCLE_ACH    = "FFF2CC"   # pale yellow  (achievement row)
    C_TIER_GREEN   = "E2EFDA"   # pale green   (% ach ≥100)
    C_TIER_ORANGE  = "FCE4D6"   # pale orange  (% ach 80–100)
    C_TIER_RED     = "FFDCE0"   # pale red     (% ach <80)
    C_TOTAL        = "EDEDED"   # grey (total row)
    C_INSENTIF     = "FFF8E7"   # cream (nilai insentif)
    C_WHITE        = "FFFFFF"

    # ---- Helper fills/fonts ----
    def fill(hex_color):
        return PatternFill("solid", fgColor=hex_color)

    def thin_border():
        s = Side(style="thin", color="BFBFBF")
        return Border(left=s, right=s, top=s, bottom=s)

    def center(wrap=False):
        return Alignment(horizontal="center", vertical="center", wrap_text=wrap)

    def right():
        return Alignment(horizontal="right", vertical="center")

    FMT_IDR  = '#,##0'
    FMT_PCT  = '0.00%'
    FMT_PCT1 = '0.00"%"'   # display as "87.35%" not 0.8735

    # ---- Column layout (matches insentif df columns) ----
    # We'll write a styled header block + data rows
    cols = list(insentif.columns)
    n_rows = len(insentif)

    # --- Group header row (row 1): merged group labels ---
    group_defs = [
        # (label, start_col_name, end_col_name, bg)
        ("SDO",            "SDO",          "SDO",          C_HEADER_DARK),
        ("ACHIEVEMENT",    "C0126",         "Total_Q1",     C_HEADER_MID),
        ("TARGET",         "Tgt_C01",       "Target_Q1",    C_HEADER_MID),
        ("CYCLE 01",       "ACH%_C01",      "Nilai_C01",    "1F497D"),
        ("CYCLE 02",       "ACH%_C02",      "Nilai_C02",    "2E75B6"),
        ("CYCLE 03",       "ACH%_C03",      "Nilai_C03",    "17375E"),
        ("Q1 SUMMARY",     "ACH_pct",       "Tier",         C_HEADER_DARK),
        ("QUARTERLY ADD",  "Tier_Quarterly","Add_Quarterly",C_HEADER_MID),
        ("TOTAL INSENTIF", "Total_Insentif","Total_Insentif",C_HEADER_DARK),
    ]

    def col_idx(name):
        return cols.index(name) + 1  # 1-based

    # Write group headers (row 1)
    for label, start_name, end_name in [(g[0], g[1], g[2]) for g in group_defs]:
        c1 = col_idx(start_name)
        c2 = col_idx(end_name)
        bg = next(g[3] for g in group_defs if g[0] == label)
        if c1 == c2:
            cell = ws.cell(row=1, column=c1, value=label)
        else:
            ws.merge_cells(start_row=1, start_column=c1, end_row=1, end_column=c2)
            cell = ws.cell(row=1, column=c1, value=label)
        cell.fill = fill(bg)
        cell.font = Font(bold=True, color="FFFFFF", size=10)
        cell.alignment = center(wrap=True)
        cell.border = thin_border()

    # Column sub-headers (row 2)
    col_labels = {
        "SDO":              "SDO",
        "C0126":            "Ach C01",
        "C0226":            "Ach C02",
        "C0326":            "Ach C03",
        "Total_Q1":         "Total Ach",
        "Tgt_C01":          "Tgt C01",
        "Tgt_C02":          "Tgt C02",
        "Tgt_C03":          "Tgt C03",
        "Target_Q1":        "Total Target",
        "ACH%_C01":         "ACH %",
        "Tier_C01":         "Tier",
        "Nilai_C01":        "Nilai",
        "ACH%_C02":         "ACH %",
        "Tier_C02":         "Tier",
        "Nilai_C02":        "Nilai",
        "ACH%_C03":         "ACH %",
        "Tier_C03":         "Tier",
        "Nilai_C03":        "Nilai",
        "ACH_pct":          "ACH % Q1",
        "Tier":             "Tier Q1",
        "Tier_Quarterly":   "Tier",
        "Add_Quarterly":    "Add Nilai",
        "Total_Insentif":   "TOTAL",
    }
    for ci, cname in enumerate(cols, start=1):
        cell = ws.cell(row=2, column=ci, value=col_labels.get(cname, cname))
        cell.fill = fill(C_HEADER_LIGHT)
        cell.font = Font(bold=True, color="1F3864", size=9)
        cell.alignment = center(wrap=True)
        cell.border = thin_border()

    # Data rows (row 3 onward)
    for ri, row_data in enumerate(insentif.iterrows(), start=3):
        _, row = row_data
        for ci, cname in enumerate(cols, start=1):
            val = row[cname]
            cell = ws.cell(row=ri, column=ci, value=val)
            cell.border = thin_border()
            cell.alignment = right() if ci > 1 else Alignment(vertical="center", indent=1)

            # Number formats
            if cname in ("C0126","C0226","C0326","Total_Q1","Tgt_C01","Tgt_C02","Tgt_C03",
                         "Target_Q1","Nilai_C01","Nilai_C02","Nilai_C03","Add_Quarterly","Total_Insentif"):
                cell.number_format = FMT_IDR
            elif "ACH%" in cname or cname == "ACH_pct":
                cell.number_format = '0.00'   # stored as raw number (87.35), show as-is
            elif cname == "Total_Insentif":
                cell.number_format = FMT_IDR
                cell.font = Font(bold=True, size=10)

            # Row background by ACH%
            ach_q1 = row["ACH_pct"]
            if cname == "Total_Insentif":
                cell.fill = fill(C_INSENTIF)
                cell.font = Font(bold=True, color="1F3864", size=10)
            elif cname == "SDO":
                cell.font = Font(bold=True, size=10)
            elif "Nilai" in cname or cname == "Add_Quarterly":
                cell.fill = fill(C_INSENTIF)
            elif "ACH%" in cname or cname == "ACH_pct":
                if ach_q1 >= 100:
                    cell.fill = fill(C_TIER_GREEN)
                elif ach_q1 >= 80:
                    cell.fill = fill(C_TIER_ORANGE)
                else:
                    cell.fill = fill(C_TIER_RED)

    # TOTAL row
    total_row = n_rows + 3
    ws.cell(row=total_row, column=1, value="TOTAL").font = Font(bold=True, color="FFFFFF", size=11)
    ws.cell(row=total_row, column=1).fill = fill(C_HEADER_DARK)
    ws.cell(row=total_row, column=1).alignment = Alignment(vertical="center", indent=1)
    ws.cell(row=total_row, column=1).border = thin_border()

    sum_cols = ["C0126","C0226","C0326","Total_Q1","Tgt_C01","Tgt_C02","Tgt_C03","Target_Q1",
                "Nilai_C01","Nilai_C02","Nilai_C03","Add_Quarterly","Total_Insentif"]
    for ci, cname in enumerate(cols, start=1):
        cell = ws.cell(row=total_row, column=ci)
        if ci == 1:
            continue
        if cname in sum_cols:
            data_start = 3
            data_end = n_rows + 2
            col_letter = get_column_letter(ci)
            cell.value = f"=SUM({col_letter}{data_start}:{col_letter}{data_end})"
            cell.number_format = FMT_IDR
        cell.fill = fill(C_TOTAL)
        cell.font = Font(bold=True, size=10)
        cell.alignment = right()
        cell.border = thin_border()

    # Column widths
    width_map = {
        "SDO": 26, "C0126": 16, "C0226": 16, "C0326": 16, "Total_Q1": 18,
        "Tgt_C01": 16, "Tgt_C02": 16, "Tgt_C03": 16, "Target_Q1": 18,
        "ACH%_C01": 9, "Tier_C01": 8, "Nilai_C01": 14,
        "ACH%_C02": 9, "Tier_C02": 8, "Nilai_C02": 14,
        "ACH%_C03": 9, "Tier_C03": 8, "Nilai_C03": 14,
        "ACH_pct": 10, "Tier": 8, "Tier_Quarterly": 8, "Add_Quarterly": 14,
        "Total_Insentif": 18,
    }
    for ci, cname in enumerate(cols, start=1):
        ws.column_dimensions[get_column_letter(ci)].width = width_map.get(cname, 14)

    # Row heights
    ws.row_dimensions[1].height = 22
    ws.row_dimensions[2].height = 30
    for r in range(3, total_row + 1):
        ws.row_dimensions[r].height = 18

    # Freeze panes: beku baris header + kolom SDO
    ws.freeze_panes = "B3"


def save_outputs(df_etl: pd.DataFrame, insentif: pd.DataFrame, pivot: pd.DataFrame) -> None:
    """Simpan file output ke folder output/."""
    print("[5/6] Saving outputs...")

    pgi_min = pd.to_datetime(df_etl["ACTUAL PGI DATE"], errors="coerce").min()
    pgi_max = pd.to_datetime(df_etl["ACTUAL PGI DATE"], errors="coerce").max()
    periode = f"{pgi_min.strftime('%Y%m%d')}_{pgi_max.strftime('%Y%m%d')}"

    # 1) ETL lengkap
    f1 = OUT_DIR / f"ZSDCONUN_ETL_{periode}.xlsx"
    with pd.ExcelWriter(f1, engine="openpyxl") as w:
        df_etl.to_excel(w, sheet_name="ZSDCONUN", index=False)
    print(f"   -> {f1.name}")

    # 2) Insentif Q1 + pivot (dengan formatting)
    f2 = OUT_DIR / f"Insentif_Q1_{periode[:4]}.xlsx"
    with pd.ExcelWriter(f2, engine="openpyxl") as w:
        pivot.to_excel(w, sheet_name="Achievement", index=False)
        # Tulis insentif tanpa header bawaan pandas (kita tulis sendiri)
        insentif.to_excel(w, sheet_name="Insentif", index=False, header=False, startrow=2)
        # Tambahkan header kolom row 1 (placeholder, akan di-overwrite oleh formatter)
        for ci, cname in enumerate(insentif.columns, start=1):
            w.sheets["Insentif"].cell(row=1, column=ci, value=cname)

    # Apply rich formatting ke sheet Insentif
    wb = load_workbook(f2)
    ws_ins = wb["Insentif"]
    _fmt_insentif_sheet(ws_ins, insentif)
    wb.save(f2)
    print(f"   -> {f2.name} (with formatting)")


# =====================================================================
# 7. MAIN
# =====================================================================

def main() -> None:
    print("=" * 70)
    print("ETL INSENTIF - ZSDCONUN -> Insentif Q1")
    print("=" * 70)

    data = load_data()
    df_etl = transform(data)
    pivot = build_pivot_q1(df_etl)

    target = _get_target_quarters(data["target"])
    insentif = hitung_insentif_q1(pivot, target)

    save_outputs(df_etl, insentif, pivot)

    print()
    print("[6/6] HASIL INSENTIF Q1")
    print()
    show_cols = [
        "SDO", "Total_Q1", "Target_Q1", "ACH_pct", "Tier",
        "Nilai_C01", "Nilai_C02", "Nilai_C03", "Add_Quarterly", "Total_Insentif",
    ]
    print(insentif[show_cols].to_string(index=False))
    print()
    print(f"Total nilai insentif Q1: Rp {insentif['Total_Insentif'].sum():,.0f}")
    print("=" * 70)
    print("DONE.")


if __name__ == "__main__":
    main()
