"""
etl_zsdconan.py
ETL Insentif - ZSDCONUN -> Achievement SDO -> Insentif Q1

Pipeline:
  1. Load source xlsx
  2. Transform (clean SDO, enrich, classify, brand dari MASTERDATA)
  3. Pivot achievement Q1 per SDO (semua channel, hanya filter nama SDO)
  4. Hitung insentif per cycle + insentif quarterly
  5. Save outputs

Author : generated by Claude
Usage  : python etl_zsdconan.py
"""

from __future__ import annotations

import warnings
from pathlib import Path

import pandas as pd

warnings.filterwarnings("ignore", category=UserWarning)

# =====================================================================
# 1. CONFIG
# =====================================================================

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
OUT_DIR = BASE_DIR / "output"
OUT_DIR.mkdir(exist_ok=True)

# Source files
FILE_ZSDCONUN = DATA_DIR / "ZSDCONUN 23112025 -30042026.xlsx"
FILE_CYCLE = DATA_DIR / "CYCLE_REKAP_1.0.xlsx"
FILE_SKU = DATA_DIR / "skuu6.xlsx"  # dipakai sheet MASTERDATA untuk Brand
FILE_CUST = DATA_DIR / "master c05.xlsx"
FILE_TARGET = DATA_DIR / "Target Modern Update KA 15 May 2026.xlsx"

# Sheet names
SHEET_ZSDCONUN = "ZSDCONUN"
SHEET_CYCLE = "Sheet2"
SHEET_SKU_MASTER = "MASTERDATA"  # kolom Brand ada di sini
SHEET_CUST = "Sheet1"
SHEET_TARGET = "Target KA (2)"

# Business constants
PPN = 1.11
Q1_CYCLES = ["C0126", "C0226", "C0326"]
Q1_CYCLE_NUM = ["C01", "C02", "C03"]
FILTER_REMARKS = ["SALES", "RETUR"]  # Claim G di-exclude dari achievement
DROP_INVALID_SO_DATE = True

# Daftar SDO yang dihitung insentifnya (semua SDO di Target KA)
SDO_INSENTIF_LIST = [
    "MARTA TEMMY NATASIA",
    "IMANUEL SIREGAR",
    "BAGUS YULIARTO",
    "ANDY",
    "AHMAD DAMYATI",
    "JEKY TIRTA",
    "MOHAMMAD HENDRA FARIZAL",
]

# Tabel tier insentif per cycle (berdasarkan ACH% per cycle)
# >= 80% - < 100%  -> 0.25%
# >= 100% - <= 110% -> 0.50%
# > 110%            -> 0.75%
TIER_CYCLE_PCT = [0.0025, 0.0050, 0.0075]
TIER_CYCLE_THRESH = [0.80, 1.00, 1.10]  # batas bawah tier

# Tabel tier insentif quarterly (ADD) — VLOOKUP dari scheme C34:D38
# Format: list of (batas_bawah_ach, nilai_add)
# Jika ach < 0.90 -> 0
# 0.90 <= ach < 1.00 -> 0.001 (0.10%)
# 1.00 <= ach < 1.05 -> 0.0025 (0.25%)
# 1.05 <= ach < 1.10 -> 0.003 (0.30%)
# ach >= 1.10       -> 0.0035 (0.35%)
TIER_QUARTERLY = [
    (0.00, 0.0000),
    (0.90, 0.0010),
    (1.00, 0.0025),
    (1.05, 0.0030),
    (1.10, 0.0035),
]


# =====================================================================
# 2. SDO CLEANING  (dipanggil diawal ETL, bukan dari merge master)
# =====================================================================

def cleaning_sdo_global(s):
    """Normalisasi nama SDO dari kolom SDO di ZSDCONUN."""
    if pd.isna(s):
        return None
    s = str(s).upper().strip()
    if "ANDY WIJAYA" in s:
        return "ANDY"
    elif "IMAM SHOVI" in s:
        return "IMAM SHOVII"
    elif "OKTO" in s:
        return "OKTO RISMAN"
    elif "ANDI MANGGALA" in s or "ANDI ARDIYANSYAH" in s:
        return "ANDI MANGGALA PUTRA"
    elif "JINO" in s:
        return "FREEKY JINO"
    elif "MUHAMMAD LANANG GALIH" in s:
        return "MUHAMMAD LANANG GALIH GUMILANG"
    elif "ABDUL JABBAR" in s:
        return "ABDUL JABAR"
    elif "MO MOHAMMAD HENDRA FARIZAL" in s:
        return "MOHAMMAD HENDRA FARIZAL"
    else:
        return s


# =====================================================================
# 3. LOAD
# =====================================================================

def load_data() -> dict:
    """Baca semua source ke dict of DataFrame."""
    print("[1/6] Loading source data...")

    data = {
        "zsdconun": pd.read_excel(FILE_ZSDCONUN, sheet_name=SHEET_ZSDCONUN, engine="openpyxl"),
        "cycle": pd.read_excel(FILE_CYCLE, sheet_name=SHEET_CYCLE, engine="openpyxl"),
        # Brand ada di sheet MASTERDATA, bukan LIST SKU
        "sku_master": pd.read_excel(FILE_SKU, sheet_name=SHEET_SKU_MASTER, engine="openpyxl"),
        "cust": pd.read_excel(FILE_CUST, sheet_name=SHEET_CUST, engine="openpyxl"),
        "target": pd.read_excel(FILE_TARGET, sheet_name=SHEET_TARGET, engine="openpyxl"),
    }

    for k, v in data.items():
        print(f"   - {k:<12s} : {len(v):>7,} rows x {len(v.columns):>3} cols")
    return data


# =====================================================================
# 4. TRANSFORM
# =====================================================================

def _clean_zsdconun(df: pd.DataFrame) -> pd.DataFrame:
    """Drop baris invalid + normalisasi tipe data + cleaning SDO."""
    df = df.copy()

    # 1) Cleaning SDO diawal (sebelum merge apapun)
    df["SDO"] = df["SDO"].apply(cleaning_sdo_global)

    # 2) Drop baris dengan SO DATE = '#VALUE!' (rusak di source)
    if DROP_INVALID_SO_DATE:
        mask_invalid = df["SO DATE"].astype(str).str.contains("VALUE", na=False)
        n_drop = int(mask_invalid.sum())
        if n_drop:
            print(f"   drop {n_drop:,} rows with invalid SO DATE")
            df = df[~mask_invalid].copy()

    # 3) ACTUAL PGI DATE → datetime
    df["ACTUAL PGI DATE"] = pd.to_datetime(df["ACTUAL PGI DATE"], errors="coerce")
    df = df.dropna(subset=["ACTUAL PGI DATE"]).reset_index(drop=True)

    # 4) Normalisasi key
    df["CUSTOMER#"] = df["CUSTOMER#"].astype(str).str.strip()
    df["MATERIAL"] = df["MATERIAL"].astype(str).str.strip()

    return df


def _build_cycle_map(cycle_df: pd.DataFrame) -> pd.DataFrame:
    """Siapkan cycle_df: kolom Cycle, Start, End sebagai datetime."""
    c = cycle_df[["Cycle", "Start Date", "End Date"]].dropna(subset=["Cycle"]).copy()
    c["Start Date"] = pd.to_datetime(c["Start Date"], errors="coerce")
    c["End Date"] = pd.to_datetime(c["End Date"], errors="coerce")
    c = c.dropna(subset=["Start Date", "End Date"]).reset_index(drop=True)
    return c


def _assign_cycle(df: pd.DataFrame, cycle_df: pd.DataFrame) -> pd.Series:
    """Untuk setiap baris, cari cycle yang ACTUAL PGI DATE-nya di antara Start–End."""
    c_sorted = cycle_df.sort_values("Start Date").reset_index(drop=True)
    starts = c_sorted["Start Date"].values
    ends = c_sorted["End Date"].values
    cycles = c_sorted["Cycle"].values
    pgi = df["ACTUAL PGI DATE"].values

    import numpy as np
    idx = np.searchsorted(starts, pgi, side="right") - 1
    result = []
    for i, ix in enumerate(idx):
        if 0 <= ix < len(cycles) and starts[ix] <= pgi[i] <= ends[ix]:
            result.append(cycles[ix])
        else:
            result.append(None)
    return pd.Series(result, index=df.index, name="CYCLE")


def _prepare_sku_master(sku_df: pd.DataFrame) -> pd.DataFrame:
    """Ambil kolom Brand, PG, SUB-PG dari sheet MASTERDATA + dedupe SKU Code."""
    s = sku_df[["SKU Code", "Brand", "PG", "SUB-PG"]].copy()
    s.columns = ["SKU Code", "BRAND_SRC", "PG_SRC", "SUBPG_SRC"]
    s["SKU Code"] = s["SKU Code"].astype(str).str.strip()
    s = s.dropna(subset=["SKU Code"])
    s = s.drop_duplicates(subset=["SKU Code"], keep="first").reset_index(drop=True)
    return s


def _prepare_cust(cust_df: pd.DataFrame) -> pd.DataFrame:
    """Ambil Chanel, SPV, ASM, RSM dari master c05 + dedupe Customer Code."""
    c = cust_df[["Customer Code", "Chanel", "SPV", "ASM", "RSM"]].copy()
    c.columns = ["CUSTOMER#", "CHANNEL_SRC", "SPV_SRC", "ASM_SRC", "RSM_SRC"]
    c["CUSTOMER#"] = c["CUSTOMER#"].astype(str).str.strip()
    c = c.dropna(subset=["CUSTOMER#"])
    c = c.drop_duplicates(subset=["CUSTOMER#"], keep="first").reset_index(drop=True)
    return c


def _classify_remarks(netvalue2: float) -> str:
    """Logika remarks: <0 RETUR, <1000 CLAIM G, >=1000 SALES."""
    if pd.isna(netvalue2):
        return None
    if netvalue2 < 0:
        return "RETUR"
    if netvalue2 < 1000:
        return "CLAIM G"
    return "SALES"


def transform(data: dict) -> pd.DataFrame:
    """Inti transformasi ZSDCONUN → ETL enriched."""
    print("[2/6] Transforming ZSDCONUN...")

    df = _clean_zsdconun(data["zsdconun"])
    print(f"   rows after clean + SDO cleaning: {len(df):,}")

    # 1) NET VALUE2 = NET VALUE × PPN
    df["NET VALUE2"] = df["NET VALUE"] * PPN

    # 2) CYCLE: lookup berdasarkan ACTUAL PGI DATE
    cycle_map = _build_cycle_map(data["cycle"])
    df["CYCLE"] = _assign_cycle(df, cycle_map)
    n_assigned = df["CYCLE"].notna().sum()
    n_total = len(df)
    print(f"   cycle assigned: {n_assigned:,} / {n_total:,} ({n_assigned/n_total*100:.1f}%)")

    # 3) BRAND, PG, SUBPG: merge MATERIAL → skuu6 MASTERDATA
    sku = _prepare_sku_master(data["sku_master"])
    df = df.merge(sku, how="left", left_on="MATERIAL", right_on="SKU Code")
    df["BRAND"] = df["BRAND_SRC"]
    df["PG"] = df["PG_SRC"]
    df["SUBPG"] = df["SUBPG_SRC"]
    df["SUBPG1"] = df["SUBPG_SRC"]  # alias
    df = df.drop(columns=["SKU Code", "BRAND_SRC", "PG_SRC", "SUBPG_SRC"], errors="ignore")

    # 4) CHANNEL: merge CUSTOMER# → master c05
    cust = _prepare_cust(data["cust"])
    df = df.merge(cust, how="left", on="CUSTOMER#")
    df["CHANNEL"] = df["CHANNEL_SRC"]
    df["SPV"] = df["SPV_SRC"]
    df["ASM"] = df["ASM_SRC"]
    df["RSM"] = df["RSM_SRC"]
    df = df.drop(columns=["CHANNEL_SRC", "SPV_SRC", "ASM_SRC", "RSM_SRC"], errors="ignore")

    # 5) REMARKS
    df["REMARKS"] = df["NET VALUE2"].apply(_classify_remarks)

    # 6) CUST_TYPE (reserved, None)
    df["CUST_TYPE"] = None

    # Susun ulang kolom sesuai output referensi
    output_cols = [
        "TYPE", "CUSTOMER#", "NAME1", "NAME2", "CUST GRP", "SALES GRP", "SDO",
        "DOCNUM", "SO DATE", "DOCDATE", "BILLINGDATE", "ACTUAL PGI DATE",
        "ITEM#", "MATERIAL", "DESCRIPTION", "ITEM CAT", "PLANT", "STORELOC",
        "QUANTITY", "SO AMOUNT", "DISCOUNT", "NET VALUE", "NET VALUE2",
        "CYCLE", "BRAND", "PG", "SUBPG", "SUBPG1", "CHANNEL", "REMARKS",
        "CUST_TYPE", "SPV", "ASM", "RSM",
    ]
    df = df.reindex(columns=output_cols)

    print(f"   ETL rows: {len(df):,}")
    return df


# =====================================================================
# 5. PIVOT & INSENTIF
# =====================================================================

def _get_target_quarters(target_df: pd.DataFrame) -> pd.DataFrame:
    """Ambil target per cycle dan Q1 per SDO."""
    t = target_df.copy()
    t.columns = [str(c).strip() for c in t.columns]
    t = t.rename(columns={t.columns[0]: "SDO"})
    t["SDO"] = t["SDO"].astype(str).str.strip().str.upper()
    t = t[t["SDO"].notna() & (t["SDO"] != "TOTAL") & (t["SDO"] != "NONE") & (t["SDO"] != "")]
    # Ambil C01–C12 per cycle
    cycle_cols = [c for c in t.columns if c.startswith("C0") and c[1:].isdigit()]
    out = t[["SDO"] + cycle_cols].copy()
    out["Target_Q1"] = out[["C01", "C02", "C03"]].sum(axis=1)
    return out.reset_index(drop=True)


def _filter_sdo_insentif(df_etl: pd.DataFrame) -> pd.DataFrame:
    """Filter hanya SDO yang ada di SDO_INSENTIF_LIST + remarks SALES/RETUR."""
    sdo_set = {s.upper().strip() for s in SDO_INSENTIF_LIST}
    df_etl = df_etl.copy()
    df_etl["SDO"] = df_etl["SDO"].astype(str).str.strip().str.upper()
    mask = df_etl["SDO"].isin(sdo_set) & df_etl["REMARKS"].isin(FILTER_REMARKS)
    return df_etl[mask].copy()


def build_pivot_q1(df_etl: pd.DataFrame) -> pd.DataFrame:
    """Pivot: SDO × cycle, filter hanya SDO di list insentif (semua channel)."""
    print("[3/6] Building pivot Q1 (filter SDO list, SALES+RETUR)...")

    filtered = _filter_sdo_insentif(df_etl)
    print(f"   filtered rows: {len(filtered):,}")

    pivot = filtered.pivot_table(
        index="SDO",
        columns="CYCLE",
        values="NET VALUE2",
        aggfunc="sum",
        fill_value=0,
    )

    # Pastikan kolom Q1 ada
    for c in Q1_CYCLES:
        if c not in pivot.columns:
            pivot[c] = 0
    pivot = pivot[Q1_CYCLES]

    # Pastikan semua SDO di list muncul walaupun 0
    pivot = pivot.reindex([s.upper().strip() for s in SDO_INSENTIF_LIST], fill_value=0)

    pivot["Total_Q1"] = pivot[Q1_CYCLES].sum(axis=1)
    pivot = pivot.reset_index()
    print(f"   pivot rows: {len(pivot)}")
    return pivot


def _tier_pct(ach_pct: float) -> str:
    """Label tier per cycle: 0.25% / 0.5% / 0.75% / -"""
    if ach_pct < TIER_CYCLE_THRESH[0] * 100:
        return "< 80%"
    if ach_pct < TIER_CYCLE_THRESH[1] * 100:
        return "0.25%"
    if ach_pct <= TIER_CYCLE_THRESH[2] * 100:
        return "0.50%"
    return "0.75%"


def _nilai_per_cycle(tier: str, target: float, ach: float) -> float:
    """Nilai insentif per cycle sesuai scheme:
       0.25% -> ach * 0.25%
       0.5%  -> target * 0.25% + (ach - target) * 0.5%
       0.75% -> target * 0.25% + (ach - target) * 0.75%
       <80%  -> 0
    """
    if tier == "0.25%":
        return ach * TIER_CYCLE_PCT[0]
    if tier == "0.50%":
        return target * TIER_CYCLE_PCT[0] + max(ach - target, 0) * TIER_CYCLE_PCT[1]
    if tier == "0.75%":
        return target * TIER_CYCLE_PCT[0] + max(ach - target, 0) * TIER_CYCLE_PCT[2]
    return 0.0


def _tier_quarterly(ach_ratio: float) -> tuple[str, float]:
    """VLOOKUP add-on quarterly: return (label, nilai_add) dari TIER_QUARTERLY."""
    # TIER_QUARTERLY sorted ascending by threshold
    for thresh, val in reversed(TIER_QUARTERLY):
        if ach_ratio >= thresh:
            return (f"{val*100:.2f}%", val)
    return ("0.00%", 0.0)


def _nilai_quarterly(ach_q1: float, target_q1: float) -> tuple[float, str, float]:
    """Insentif quarterly (ADD):
       ach_ratio = ach_q1 / target_q1
       if ach_ratio < 0.90 -> 0
       else -> (target_q1 * 0.10%) + (ach_q1 - target_q1) * tier_value
    """
    if target_q1 <= 0:
        return (0.0, "0.00%", 0.0)
    ach_ratio = ach_q1 / target_q1
    label, val = _tier_quarterly(ach_ratio)
    if ach_ratio < TIER_QUARTERLY[1][0]:  # < 0.90
        return (0.0, label, ach_ratio)
    if ach_ratio < 1.00:
        return (ach_q1 * val, label, ach_ratio)
    # ach_ratio >= 1.00
    return (target_q1 * 0.001 + max(ach_q1 - target_q1, 0) * val, label, ach_ratio)


def hitung_insentif_q1(pivot: pd.DataFrame, target_df: pd.DataFrame) -> pd.DataFrame:
    """Hitung insentif Q1 per SDO:
       - per cycle (3 kolom cycle)
       - quarterly add-on
       - total
    """
    print("[4/6] Menghitung insentif Q1 (per cycle + quarterly)...")

    pivot = pivot.copy()
    target_df = target_df.copy()
    pivot["SDO"] = pivot["SDO"].astype(str).str.strip().str.upper()
    target_df["SDO"] = target_df["SDO"].astype(str).str.strip().str.upper()

    # Pastikan urutan SDO sesuai SDO_INSENTIF_LIST
    pivot = pivot.set_index("SDO")
    sdo_order = [s.upper().strip() for s in SDO_INSENTIF_LIST]
    pivot = pivot.reindex(sdo_order, fill_value=0).reset_index()

    # Merge target
    target_q1 = target_df[["SDO", "C01", "C02", "C03"]].copy()
    target_q1.columns = ["SDO", "Tgt_C01", "Tgt_C02", "Tgt_C03"]
    merged = pivot.merge(target_q1, on="SDO", how="left").fillna(0)

    # Hitung per cycle
    for i, cyc in enumerate(Q1_CYCLES):
        tgt_col = f"Tgt_{Q1_CYCLE_NUM[i]}"
        ach_col = cyc
        pct_col = f"ACH%_{Q1_CYCLE_NUM[i]}"
        tier_col = f"Tier_{Q1_CYCLE_NUM[i]}"
        nilai_col = f"Nilai_{Q1_CYCLE_NUM[i]}"

        merged[pct_col] = merged.apply(
            lambda r: (r[ach_col] / r[tgt_col] * 100) if r[tgt_col] > 0 else 0.0,
            axis=1,
        )
        merged[tier_col] = merged[pct_col].apply(_tier_pct)
        merged[nilai_col] = merged.apply(
            lambda r: _nilai_per_cycle(r[tier_col], r[tgt_col], r[ach_col]),
            axis=1,
        )

    # Total & ACH% Q1
    merged["Target_Q1"] = merged[["Tgt_C01", "Tgt_C02", "Tgt_C03"]].sum(axis=1)
    merged["Ach_Q1"] = merged["Total_Q1"]
    merged["ACH_pct"] = merged.apply(
        lambda r: (r["Ach_Q1"] / r["Target_Q1"] * 100) if r["Target_Q1"] > 0 else 0.0,
        axis=1,
    )

    # Insentif quarterly (ADD)
    q_results = merged.apply(
        lambda r: _nilai_quarterly(r["Ach_Q1"], r["Target_Q1"]),
        axis=1,
    )
    merged["Tier_Quarterly"] = [q[1] for q in q_results]
    merged["Add_Quarterly"] = [q[0] for q in q_results]
    merged["ACH_ratio"] = [q[2] for q in q_results]

    # Total insentif = jumlah 3 cycle + ADD quarterly
    merged["Total_Insentif"] = (
        merged["Nilai_C01"] + merged["Nilai_C02"] + merged["Nilai_C03"] + merged["Add_Quarterly"]
    )

    # Tier ringkasan Q1 (berdasarkan ACH_pct Q1)
    merged["Tier"] = merged["ACH_pct"].apply(_tier_pct)

    # Susun kolom output
    out_cols = [
        "SDO",
        "C0126", "C0226", "C0326", "Total_Q1",
        "Tgt_C01", "Tgt_C02", "Tgt_C03", "Target_Q1",
        "ACH%_C01", "Tier_C01", "Nilai_C01",
        "ACH%_C02", "Tier_C02", "Nilai_C02",
        "ACH%_C03", "Tier_C03", "Nilai_C03",
        "ACH_pct", "Tier",
        "Tier_Quarterly", "Add_Quarterly",
        "Total_Insentif",
    ]
    merged = merged[out_cols].sort_values("ACH_pct", ascending=False).reset_index(drop=True)
    return merged


# =====================================================================
# 6. SAVE
# =====================================================================

def save_outputs(df_etl: pd.DataFrame, insentif: pd.DataFrame, pivot: pd.DataFrame) -> None:
    """Simpan file output ke folder output/."""
    print("[5/6] Saving outputs...")

    pgi_min = pd.to_datetime(df_etl["ACTUAL PGI DATE"], errors="coerce").min()
    pgi_max = pd.to_datetime(df_etl["ACTUAL PGI DATE"], errors="coerce").max()
    periode = f"{pgi_min.strftime('%Y%m%d')}_{pgi_max.strftime('%Y%m%d')}"

    # 1) ETL lengkap
    f1 = OUT_DIR / f"ZSDCONUN_ETL_{periode}.xlsx"
    with pd.ExcelWriter(f1, engine="openpyxl") as w:
        df_etl.to_excel(w, sheet_name="ZSDCONUN", index=False)
    print(f"   -> {f1.name}")

    # 2) Insentif Q1 + pivot
    f2 = OUT_DIR / f"Insentif_Q1_{periode[:4]}.xlsx"
    with pd.ExcelWriter(f2, engine="openpyxl") as w:
        pivot.to_excel(w, sheet_name="Achievement", index=False)
        insentif.to_excel(w, sheet_name="Insentif", index=False)
    print(f"   -> {f2.name}")


# =====================================================================
# 7. MAIN
# =====================================================================

def main() -> None:
    print("=" * 70)
    print("ETL INSENTIF - ZSDCONUN -> Insentif Q1")
    print("=" * 70)

    data = load_data()
    df_etl = transform(data)
    pivot = build_pivot_q1(df_etl)

    target = _get_target_quarters(data["target"])
    insentif = hitung_insentif_q1(pivot, target)

    save_outputs(df_etl, insentif, pivot)

    print()
    print("[6/6] HASIL INSENTIF Q1")
    print()
    show_cols = [
        "SDO", "Total_Q1", "Target_Q1", "ACH_pct", "Tier",
        "Nilai_C01", "Nilai_C02", "Nilai_C03", "Add_Quarterly", "Total_Insentif",
    ]
    print(insentif[show_cols].to_string(index=False))
    print()
    print(f"Total nilai insentif Q1: Rp {insentif['Total_Insentif'].sum():,.0f}")
    print("=" * 70)
    print("DONE.")


if __name__ == "__main__":
    main()
